title: "Behavioral Network Science: Language, Mind, and Society"
description: Resources for 'Behavioral Network Science: Language, Mind, and Society' by Thomas T. Hills
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
